import type { Metadata } from 'next';
import './globals.css';
import iranSans from '@/config/localFont';
import { ReactNode } from 'react';
import { AppProvider } from '@/providers';
import { cn } from '@/lib';
import { FooterSection } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: ReactNode;
  authModal: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn(`${iranSans.className} ${iranSans.variable}`)}>
        {/* <ThemeProvider > */}
        <main>
          <AppProvider>
            {authModal}
            {children}
            <FooterSection className={cn('mt-[70px]')} />
          </AppProvider>
          <div id="portal-root" />
        </main>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
